apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer
